name: Build wheels
run-name: Build platform wheels on Linux
on:
  workflow_call:

jobs:
  Build-Wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build setuptools wheel
        python -m pip install git+https://bitbucket.org/vmorello/mtcutils.git@master
        make install
    - name: Build wheels
      run: python -m build --wheel --outdir dist
    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./dist/
