name: Build and upload
run-name: Build platform wheels and upload them to PyPI
on:
  workflow_dispatch:

jobs:
  Build-workflow:
    uses: fjankowsk/scatfit/.github/workflows/build-wheels.yml@master

  Upload-workflow:
    needs: Build-workflow
    uses: fjankowsk/scatfit/.github/workflows/upload-wheels-pypi.yml@master
