name: Build and upload
run-name: Build platform wheels and upload them to PyPI
on:
  push:
    branches: [ master ]

jobs:
  Build-workflow:
    uses: fjankowsk/scatfit/.github/workflows/build-wheels.yml@master

  Upload-workflow:
    needs: Build-workflow
    uses: fjankowsk/scatfit/.github/workflows/upload-wheels-testpypi.yml@master
