name: Scatfit

on:
  push:
    branches: [ master ]

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

  steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pytest pytest-cov
        make install
    - name: Test project with pytest
      run: |
        make test
