name: Upload wheels PyPI
run-name: Upload platform wheels to PyPI
on:
  workflow_call:

jobs:
  Upload-Wheels:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/scatfit
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - name: Download wheel artifacts
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: ./dist/
    - name: Upload wheels to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
